### ISSUE TITLE
Publish Clibsodium XCFramework?

### ISSUE THREAD

**Issue by mrosales** [jedisct1/swift-sodium#210]
There is a `Clibsodium.xcframework` file checked in on the master branch, but the `cocoapod` podspec still only points at the last tagged `0.8.0` release.

It seems like several issues (namely #205) relating to unexpected Xcode 12 behaviors were resolved referencing the using the xcframework, which is not yet set up via cocoapods.

Do you have plans to begin publishing the `Clibsodium.xcframework` file with cocoapods so it can be used as a dependency of the `Sodium` pod?

**Comment by jedisct1** [comment]
Hi,

I don't use Cocoapods; do you know how to do that?

A quick look at the documentation suggests adding a `vendored_frameworks` property, so I added:

```text
s.vendored_frameworks = 'Clibsodium.xcframework'
```

And bumped `ios_deployment_target` to `9.0`, but `pod lib lint` complains:

```text
    - ERROR | xcodebuild:  swift-sodium/Sodium/Aead.swift:2:8: error: no such module 'Clibsodium'
```

What should I do?

**Comment by mrosales** [comment]
I set up a minimal example in a [personal github repo](https://github.com/mrosales/Clibsodium-xcframework) that just has the `Clibsodium.xcframework` and `Clibsodium.podspec` file.

Using this I was able to build a project that vendors the `swift-sodium` code.

I think a reasonable way to set this up with cocoapods would be:

1. Set up an official release of `Clibsodium.xcframework`. It could be pulled from this repo, but having it attached to a tag or github release would probably be best. (I think that is best practice to avoid committing the binaries for SPM too)
2. Publish a new `Clibsodium` pod that uses `vendored_frameworks` to distribute the `xcframework` (kind of like my example github repo)
3. Modify the swift `Sodium` pod to declare a dependency on `Clibsodium` instead of vendoring the `.a` file and headers.

I haven't done much investigation into other projects, but another similar one I've used before is the [`TensorflowliteSwift`](https://cocoapods.org/pods/TensorFlowLiteSwift) ([podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/d/9/6/TensorFlowLiteSwift/2.3.0/TensorFlowLiteSwift.podspec.json)) project which has a dependency on `TensorflowliteC`, with the latter just vendoring a static library.

I'm happy to help, but I think a good deal of it might just be setting up a new repo/pod distribution.

**Comment by jedisct1** [comment]
With `s.vendored_frameworks = 'Clibsodium.xcframework'` in the main pod file, the framework seems to be found (at least, changing it to a non-existent directory raises an error).

But `pod lib lint` outputs `xcodebuild:  swift-sodium/Sodium/Aead.swift:2:8: error: no such module 'Clibsodium'`

**Comment by jedisct1** [comment]
> Modify the swift Sodium pod to declare a dependency on Clibsodium instead of vendoring the .a file and headers.

How to do that?

**Comment by mrosales** [comment]
OK I set up a fork that I was able to get building like I had outlined. To test this, I added both podspecs to a local repo and then made a sample project that used `pod Sodium` and I was able to successfully run some sodium operations.

https://github.com/jedisct1/swift-sodium/compare/master...mrosales:master

One change that might be unexpected is adding all of the `public init() {}` initializers. I'm not strictly sure if that is necessary, but when integrating against the built product. It was considering the synthesized initializers to have `internal` scope and therefore be unusable. I imagine that building the library as a static library with BUILD_FOR_DISTRIBUTION caused this and its required to ensure that changes in synthesized stored properties wouldn't produce an incompatible binary.

**Comment by jedisct1** [comment]
I wasn't able to use your repository either:

```sh
$ pod lib lint Clibsodium.podspec

    - NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in ' false ios-arm64_x86_64-maccatalyst/libsodium.a ios-i386_x86_64-simulator/libsodium.a ios-arm64_armv7_armv7s/libsodium.a' for the current build architectures (arm64 i386 x86_64).
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Since the Swift Package Manager works out of the box and seems to be the recommended package manager for portable libraries, is is really worth trying to support Cocoapods?

**Comment by mrosales** [comment]
I believe that's a bug in CocoaPods https://github.com/CocoaPods/CocoaPods/issues/10026 that is only fixed in the latest 1.10.0.rc.1 version.

I also think there's another CP bug that was preventing the `Sodium` podspec from working properly. I had to manually add the `HEADER_SEARCH_PATHS` and `LIBRARY_SEARCH_PATHS` variables even though cocoapods should normally handle that. It seems like they were only added to the application target but not the `Sodium` target so the compiler wasn't discovering the Clibsodium library.

I agree that SPM is probably the way of the future, and its your call whether or not you'd like to retain active support for Cocoapods, but if you don't want to, I think you should add some disclaimers to the readme, because the currently published Sodium 0.8.0 CocoaPod is no longer working on Xcode 12. 

```
$ pod --version
1.10.0.rc.1

$ pod lib lint --allow-warnings Clibsodium.podspec 

 -> Clibsodium (1.0.18)
    - WARN  | source: Git sources should specify a tag.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')

Clibsodium passed validation.


$ pod lib lint --allow-warnings --sources=local Sodium.podspec

 -> Sodium (0.9.0)
    - WARN  | source: Git sources should specify a tag.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Sodium' from project 'Pods')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')

Sodium passed validation.
```

**Comment by jedisct1** [comment]
Fixed by 72077b7b082f1f1b5a060569593ffb5886111b12

**Comment by mrosales** [comment]
Great, thanks @jedisct1 and @Westacular for working on this. Before the book is closed on this, can you push out the updated podspec to the ccocoapods trunk repo?

**Comment by jedisct1** [comment]
This still doesn't work with the current version of Cocoapods, or even with the 1.10.0.rc version.

Wes submitted a PR to fix a Cocoapods bug, that will hopefully be in the final 10.0.0 release. I'd rather wait for it than push a version that no one can use or that may even not be compatible any more with the 10.0.0 release.

**Comment by nielsandriesse** [comment]
I got this to work by using CocoaPods 1.10.0.rc.1 with the `--use-libraries` flag
